packages:
  - ./cdk
  - ./docs

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild

overrides:
  ajv@<8.18.0: '>=8.18.0'
  diff@<8.0.3: '>=8.0.3'
  minimatch@<10.2.1: '>=10.2.1'
  seroval@<1.4.1: '>=1.4.1'
  seroval@<=1.4.0: '>=1.4.1'
